ARG tomcat_version=tomcat:8-jdk17-temurin
FROM eclipse-temurin:17 AS build

WORKDIR /workspace/app

ARG ID_LOG_VERSION=1.0.0-SNAPSHOT
COPY mvnw .
COPY .mvn .mvn
COPY pom.xml .
COPY src src
COPY libs libs

RUN ./mvnw install:install-file -Dfile=libs/id-log-${ID_LOG_VERSION}.jar -DgroupId=ee.ria.commons -DartifactId=id-log -Dversion=${ID_LOG_VERSION} -Dpackaging=jar -DgeneratePom=true

RUN ./mvnw package

FROM $tomcat_version

COPY --from=build /workspace/app/target/tim.war /usr/local/tomcat/webapps/ROOT.war

EXPOSE 8080
EXPOSE 8443

CMD ["catalina.sh", "run"]
